### ISSUE TITLE
Explaination how to start ?

### ISSUE THREAD

**Issue by yazeed44** [nixtabyte/JTeleBot-Core#2]

**Comment by jsedano** [comment]
Hi!, we made a video tutorial, please check it out and let us know if that helps:
https://www.youtube.com/watch?v=xB_QeZm7dFY
Resources and extra information can be found here:
http://roadtonerdvana.com/2015/07/13/how-to-create-telegram-bots/

**Comment by yazeed44** [comment]
Seems helpful , i would have preferred text-based tutorial though

**Comment by jsedano** [comment]
We are working on a text based tutorial, for our next release coming this week, probably ..
